Shop.MVC/Models/CartViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Shop.MVC.Models
{
    public class CartViewModel
    {

        /// <summary>
        /// Identificador de la compra
        /// </summary>
        /// 
        [Key]
        public int Id { get; set; }





        /// <summary>
        /// Identificador del usuario que ha realizado la compra
        /// </summary>
        public string User_Id { get; set; }


        /// <summary>
        /// Colección de productos
        /// </summary>
        public virtual List<CartItemList> CartItems { get; set; }



    }
}

Shop.MVC/Controllers/CartsController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Shop.CORE;
using Shop.DAL;
using Shop.CORE.Contracts;
using Shop.MVC.Models;
using System.IO;
using Shop.IFR.Tools;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using Microsoft.AspNet.Identity.Owin;
using System.Configuration;
using Shop.IFR.Logging;

namespace Shop.MVC.Controllers
{
    [ExceptionHandler]
    public class CartsController : Controller
    {
        //private ApplicationDbContext db = new ApplicationDbContext();
        IProductManager productManager = null;
        IOrderManager orderManager = null;
        SessionController session = null;
        
        public CartsController(IProductManager productManager, IOrderManager orderManager)
        {
            this.productManager = productManager;
            this.orderManager = orderManager;
            this.session = new SessionController();
        }

        //*******************************************METODO DE LISTADOS DE ITEMS EN CARRO *************************************************************
        /// <summary>
        /// METODO QUE RETORNA LAS LINEAS DEL CARRO DE LA SESION
        /// </summary>
        /// <returns></returns>
        // GET: Carts
        public ActionResult Index()
        {
            try
            {
                if (this.session.getCartItems() != null)
                {
                    var items = this.session.getCartItems()
                        .Select(e => new CartItemList
                        {
                            ItemId = e.Id,
                            ProductId = e.ProductId,
                            User_Id = e.User_Id,
                            //CartId = e.Cart_Id,
                            Description = e.Description,
                            Price = e.Price,
                            Quantity = e.Quantity,
                            Subtotal = e.Quantity * e.Price,
                        });

                    if (items == null)
                    {
                        //return RedirectToAction("Contact", "Home");
                        return HttpNotFound();
                    }
                    else
                    {
                        decimal total = items.Sum(s => s.Subtotal);
                        ViewBag.Total = total;

                        return View(items);
                    }
                } else
                {
                    return View();
                }

            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }



        //*******************************************METODOS BOORRA ITEMS DEL CARRO ************************************************

        /// <summary>
        /// METODO GET PARA BORRA LINEAS DEL CARRO DE LA SESION
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>

        // GET: Carts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //Eliminacion de lineas
            this.session.removeCartItemByProductId(id.Value);

            return RedirectToAction("Index");

        }
    }
}





//var stripePublishKey = ConfigurationManager.AppSettings["stripePublishableKey"];
//ViewBag.StripePublishKey = stripePublishKey;               
//https://msdn.microsoft.com/es-es/library/6sh2ey19(v=vs.110).aspx
//https://msdn.microsoft.com/en-us/library/t16fe6f4(v=vs.120).aspx

Shop.MVC/Views/Carts/Create.cshtml
@model Shop.CORE.Cart

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cart</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.User_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User_Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Shop.MVC/Views/Carts/Index.cshtml
@model IEnumerable<Shop.MVC.Models.CartItemList>

@{
    ViewBag.Title = "Index";
}


@section Styles {
    <link href="@Url.Content("~/Content/DataTables/css/jquery.dataTables.css")" rel="stylesheet" type="text/css" />
}

<h2>Carrito</h2>
<hr style="width: 100%; background-color: black; height: 1px; border-color : transparent;" />


@*<label id=" labelId">
    @Html.DisplayNameFor(model => model.CartId)
    </label>

    @Html.DisplayFor(model => model.Last().CartId, new { id = "MyId" })*@

@using (Html.BeginForm("Index", "Carts"))
{
    @Html.AntiForgeryToken()




    <table id="Table" class="table display">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ItemId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ProductId)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Quantity)

                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Subtotal)

                </th>
                <th>

                </th>
            </tr>
        </thead>

        <tfoot>
            <tr>
                <th colspan="5" style="text-align:right">Total:</th>
                <th></th>
                <th></th>
            </tr>
        </tfoot>

        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="col-md-1">
                        @Html.DisplayFor(modelItem => item.ItemId)
                    </td>
                    <td class="col-md-1">
                        @Html.DisplayFor(modelItem => item.ProductId)
                    </td>
                    <td class="col-md-1">
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td class="col-md-2">
                        @Html.DisplayFor(modelItem => item.Price)

                    </td>
                    <td class="col-md-4">
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                    <td class="col-md-4">
                        @Html.DisplayFor(modelItem => item.Subtotal)
                    </td>

                    <td>

                        @Html.ActionLink("Borrame", "Delete", new { id = item.ProductId })

                    </td>
                </tr>
            }

        </tbody>

    </table>

    @*@Html.ActionLink("Button text", "Create", "Orders", new { id = (ViewBag.Total) })*@




    <hr style="width: 100%; background-color: black; height: 1px; border-color : transparent;" />


    @*@ViewBag.Total*@
    @*@Html.HiddenFor(model => model.First().CartId) != null)*@

    <div class="form-group">
        @if (User.IsInRole("Client"))
        {
            if (ViewBag.Total != null && ViewBag.Total > 0)
            {
                <div class="col-md-offset-2 col-md-6">
                    <button type="button"
                            class="btn btn-primary"
                            title="Action description" onclick='window.location = " @Url.Action("Create", "Orders") ";'>
                        Realizar Pago
                    </button>
                </div>
            }
        }

        @if (!User.Identity.IsAuthenticated)
        {
            <h2>@Html.ActionLink("Inicia sesión para realizar el pago", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</h2>
        }


    </div>

    <hr style="width: 100%; background-color: white; height: 1px; border-color : transparent;" />

}


@section Scripts {
    <script src="~/Scripts/DataTables/jquery.dataTables.js"></script>
    <script>
        $(document).ready(function () {
            $('#Table').DataTable({
                "footerCallback": function (row, data, start, end, display) {
                    var api = this.api(), data;

                    // Remove the formatting to get integer data for summation
                    var intVal = function (i) {
                        return typeof i === 'string' ?
                            i.replace(/[\$,]/g, '') * 1 :
                            typeof i === 'number' ?
                            i : 0;
                    };

                    // Total over all pages
                    total = api
                        .column(5)
                        .data()
                        .reduce(function (a, b) {
                            return intVal(a) + intVal(b);
                        }, 0);

                    // Total over this page
                    pageTotal = api
                        .column(5, { page: 'current' })
                        .data()
                        .reduce(function (a, b) {
                            return intVal(a) + intVal(b);
                        }, 0);

                    // Update footer
                    $(api.column(5).footer()).html(
                         pageTotal / 100 + ' €' + ' (' + total / 100 + ' € total)'
                    );
                }
            });
        });
    </script>

}